### ISSUE TITLE
2.编译ygo的so NDK

### ISSUE THREAD

**Issue by Clvers** [purerosefallen/YGOMobile#3]
NDKR15b set Path 
use ndk-build -j4

**Comment by Clvers** [comment]
C:\Users\Clvers\Desktop\YGOMobile-master\libcore>ndk-build
Android NDK: jni/../../Classes/sqlite3/Android.mk: Cannot find module with tag '
ocgcore' in import path
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?

Android NDK: The following directories were searched:
Android NDK:
jni/Android.mk:96: *** Android NDK: Aborting.    .  Stop.

C:\Users\Clvers\Desktop\YGOMobile-master\libcore>

**Comment by Clvers** [comment]
C:\Users\Clvers\Desktop\YGOMobile-master\libcore>ndk-build -j4
Android NDK: WARNING:jni/../../Classes/openssl/crypto/Android.mk:crypto_static: LOCAL_LDLIBS is always ignored for static libraries
[armeabi-v7a] Compile++ thumb: YGOMobile <= android_tools.cpp
[armeabi-v7a] Compile++ thumb: YGOMobile <= xstring.cpp
[armeabi-v7a] Compile++ thumb: YGOMobile <= TouchEventTransferAndroid.cpp
[armeabi-v7a] Compile++ thumb: YGOMobile <= CAndroidGUIEditBox.cpp
cc1plus.exe: error: unrecognized command line option '-mno-unaligned-access'
cc1plus.exe: error: unrecognized command line option '-mno-unaligned-access'
make.exe: *** [obj/local/armcc1plus.exe: error: unrecognized command line option '-mno-unaligned-access'
eabicc1plus.exe: error: unrecognized command line option '-mno-unaligned-access'
-v7a/objs/YGOMobile/jni/__/android/android_tools.o] Error 1
make.exe: *** Waiting for unfinished jobs....
make.exe: *** [obj/local/armeabi-v7a/objs/YGOMobile/jni/__/android/xstring.o] Error 1
make.exe: *** [obj/local/armeabi-v7a/objs/YGOMobile/jni/__/android/TouchEventTransferAndroid.o] Error 1
make.exe: *** [obj/local/armeabi-v7a/objs/YGOMobile/jni/__/android/CAndroidGUIEditBox.o] Error 1

**Comment by purerosefallen** [comment]
see `.travis.yml` for build instructions
